name: Dooray Morning Bot

on:
  schedule:
    # 한국 시간(KST) 오전 9시 46분에 작동합니다. (세계 표준시 UTC 기준 0시 46분)
    - cron: '46 0 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Morning Greeting to Dooray
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"text": "재국님, 본사신가요?"}' \
          "https://gravity.dooray.com/services/2592578758829202186/4326990432273056233/WYgU-6nIR_SI7qrotizmwQ"
