name: Dooray Morning Bot

on:
  schedule:
    # 한국 시간 오전 10시 05분 실행 (영국 시간 UTC 1시 05분)
    - cron: '5 1 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Morning Greeting to Dooray
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"text": "재국님, 본사신가요?"}' \
          "https://gravity.dooray.com/services/2592578758829202186/4326990432273056233/WYgU-6nIR_SI7qrotizmwQ"
